import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/Provider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// ✅ Optional: Global socket setup

import SocketListener from "@/components/SocketListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* ✅ Toast Container (global) */}
          <ToastContainer position="top-center" autoClose={3000} />
          {/* ✅ Global socket event listener (notifications) */}
          <SocketListener />

          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
