export const multiTokenDEXABI = [
  "function pools(bytes32) view returns (address tokenA, address tokenB, uint256 reserveA, uint256 reserveB, bool exists)",
  "function poolIds(uint256) view returns (bytes32)",
  "function totalLiquidity(bytes32) view returns (uint256)",
  "function liquidityShares(bytes32, address) view returns (uint256)",
  "function feePercent() view returns (uint256)",
  "function getPoolId(address tokenA, address tokenB) pure returns (bytes32)",
  "function createPool(address tokenA, address tokenB) returns (bytes32)",
  "function addLiquidity(address tokenA, address tokenB, uint256 amountA, uint256 amountB) returns (uint256 liquidity)",
  "function removeLiquidity(address tokenA, address tokenB, uint256 liquidity) returns (uint256 amountA, uint256 amountB)",
  "function swap(address tokenIn, address tokenOut, uint256 amountIn, uint256 minAmountOut) returns (uint256 amountOut)",
  "function getAmountOut(uint256 amountIn, uint256 reserveIn, uint256 reserveOut) view returns (uint256)",
  "function getReserves(address tokenA, address tokenB) view returns (uint256 reserveA, uint256 reserveB)",
  "function getPrice(address tokenA, address tokenB) view returns (uint256)",
  "function getAllPools() view returns (bytes32[] memory)",
  "function getUserLiquidity(address tokenA, address tokenB, address user) view returns (uint256)",
  "event PoolCreated(bytes32 indexed poolId, address tokenA, address tokenB)",
  "event LiquidityAdded(bytes32 indexed poolId, address indexed provider, uint256 amountA, uint256 amountB, uint256 liquidity)",
  "event LiquidityRemoved(bytes32 indexed poolId, address indexed provider, uint256 amountA, uint256 amountB, uint256 liquidity)",
  "event TokensSwapped(bytes32 indexed poolId, address indexed user, address tokenIn, uint256 amountIn, uint256 amountOut)",
];
